### ISSUE TITLE
Jewel disappears

### ISSUE THREAD

**Issue by jangerritharms** [asgill/SEM-25#65] opened 2015-10-06 08:05 UTC
I am not exactly sure how it happend but at some point one jewel disappeared and the game went on. This might happen because I reacted to fast and made a move while jewels were still falling down.  Maybe we should disable selection while the jewels are animated. <bug

**Comment by lange88** [comment] 2015-10-06 18:51
I managed to reproduce itby clicking really fast so I think your conclusion is right

**Comment by lange88** [comment] 2015-10-08 12:24
Closed by #66

**Comment by lange88** [comment] 2015-10-12 14:13
This is possible again because you can remove Jewels before the board is done animating..

**Closed** 2015-10-16 19:28 UTC
Labels: bug
